name: API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - uses: docker/setup-buildx-action@v3
      - name: Run tests
      - run: dotnet test